const actionName = {
  
  GET_STUDENTS: "GET_STUDENTS",
  ADD_STUDENT: "ADD_STUDENTS",
  DELETE_STUDENT: "DELETE_STUDENTS",
  EDIT_STUDENT: "EDIT_STUDENTS",
  GET_STUDENT_BY_ID: "GET_STUDENT_BY_ID",


  GET_USERS: "GET_USERS",
  ADD_USER: "ADD_USER",
  DELETE_USER: "DELETE_USER",
  EDIT_USER: "EDIT_USER",
  GET_USER_BY_ID: "GET_USER_BY_ID",


  GET_CLASSROOM: "GET_CLASSROOM",
  ADD_CLASSROOM: "ADD_CLASSROOM",
  DELETE_CLASSROOM: "DELETE_CLASSROOM",
  EDIT_CLASSROOM: "EDIT_CLASSROOM",
  GET_CLASSROOM_BY_ID: "GET_CLASSROOM_BY_ID",

}

export default actionName